---
# Add users and groups
- name: "Create user groups"
  group:
    name: "{{ item }}"
    state: "present"
  with_items:
    - admin
    - ops
- name: "Create ops-user account"
  user:
    name: "ops-user"
    groups: "admin,ops"
- name: "Create user accounts and add users to groups"
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
  with_items: "{{ users }}"
- name: "Add authorized keys"
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', 'public_keys/'+ item.username + '.key.pub') }}"
  with_items: "{{ users }}"
